import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Lottie from 'lottie-react-web';
import animationData from '../public/unserConstruction.json';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Bugide | Simplifying the World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.lottie}>
          <Lottie
            options={{
              animationData,
            }}
          />
        </div>
        <div className={styles.content}>
          <h1>Website</h1>
          <span>is</span>
          <h1>Under Construction</h1>
          <span>We'll be back soon</span>
        </div>
      </main>
    </>
  )
}
